### ISSUE TITLE
Mention option to disable progressbar for batch jobs

### ISSUE THREAD

**Issue by Flamefire** [tud-zih-ki/DeepSpeedExamples#7]
PyTorch uses TQDM for displaying training progress which is incredibly annoying when used in batch jobs where the output is redirected to a file as it appends each update instead of modifying the line which means a lot (thousands) of things like this on a single line in the output:

```
t/s]^M100%|█████████▉| 10326/10347 [51:29<00:06,  3.37it/s]^M100%|█████████▉| 10327/10347 [51:29<00:05,  3.37it/s]^M100%|█████████▉| 10328/10347 [51:30<00:05,  3.37it/s]^M100%|█████████▉| 10329/10347 [51:30<0
0:05,  3.37it/s]^M100%|█████████▉| 10330/10347 [51:30<00:05,  3.37it/s]^M100%|█████████▉| 10331/10347 [51:31<00:04,  3.38it/s]^M100%|█████████▉| 10332/10347 [51:31<00:04,  3.38it/s]^M100%|█████████▉| 10333/10
347 [51:31<00:04,  3.37it/s]^M100%|█████████▉| 10334/10347 [51:31<00:03,  3.37it/s]^M100%|█████████▉| 10335/10347 [51:32<00:03,  3.37it/s]^M100%|█████████▉| 10336/10347 [51:32<00:03,  3.37it/s]^M100%|████████
█▉| 10337/10347 [51:32<00:02,  3.37it/s]^M100%|█████████▉| 10338/10347 [51:33<00:02,  3.37it/s]^M100%|█████████▉| 10339/10347 [51:33<010360 [51:29<00:05,  3.37it/s]^M100%|█████████▉| 10342/10360 [51:30<00:05,
```

After a lot of searching I found a way to disable the progressbar via an environment variable: `export TQDM_DISABLE=1`

I think it makes sense to set that in the `*_tud.sh` and `*_slurm.sh` scripts in https://github.com/tud-zih-ki/DeepSpeedExamples/tree/gpu_bench/training/bing_bert as those are meant to run in SLURM jobs.

Or at least mention this variable in the readme at https://github.com/tud-zih-ki/DeepSpeedExamples/blob/gpu_bench/training/bing_bert/INSTALL.md

**Comment by NanoNabla** [comment]
Thanks @Flamefire
